---
title: "Strings And Factors"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(rvest)
library(httr)

library(p8105.datasets)

# General figure set up
knitr::opts_chunk$set(
  # display the code in github doc
  echo = TRUE,
  # hide warning messages
  warning = FALSE,
  # set the figure to be 8 x 6, and the proportion it takes to be 95%
  fig.width = 8,
  fig.height = 6, 
  out.width = "90%"
)

# setting a global options for continuous data color family and a different format to set discrete data to have a color family
options(
  ggplot2.countinuous.colour = "viridis",
  ggplot2.countinuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

# have a minimal theme and legends at the bottom
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## String and Regex

```{r }
# case sensitive
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "m")
str_replace(string_vec, "e", "This is an uppercase E")
# replace with empty space
str_replace(string_vec, "e", "")
```

```{r }
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
)

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think")
str_detect(string_vec, "i think$")
```

```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "bush")
str_detect(string_vec,"[Bb]ush")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

# a number followed by a lowercase letter/an uppercase letter
str_detect(string_vec, "^[0-9][a-zA-Z]")
```

The character `.` matches anything.

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
```

Looking for bracket...

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )
# double slash
str_detect(string_vec, "\\[")
```

# Why Fators are weird

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex

as.numeric(vec_sex)

vec_sex = fct_relevel(vec_sex, "male")
vec_sex
as.numeric(vec_sex)
```

## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj = 
  read_html(nsduh_url) %>% 
  html_table() %>% 
  first() %>%
  slice(-1)
```

let's clean this up!

```{r}
marj_df <-
  table_marj %>%
  # select all columns except those with P Value
  select(-contains("P Value")) %>%
  # select all columns except "State"
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent") %>%
  separate(age_year, into = c("age", "year"), "\\(") %>%
  # or separate(age_year, into = c("age", "year"), -11)
  mutate(
    year = str_replace(year, "\\(", ""),
    precent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)
  ) %>%
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

Do dataframe stuff

```{r}
marj_df %>%
  filter(age == "12-17") %>%
  mutate(
    State = fct_reorder(State, percent)
  ) %>%
  ggplot(aes(x = State, y = percent, color = year)) + 
    geom_point() + 
    # rotate text
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## Resturants Inspections

```{r}
data("rest_inspec")
```

```{r}
rest_inspec %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  pivot_wider(names_from = grade, values_from = n)
```

```{r}
rest_inspec <-
  rest_inspec %>%
  filter(
    str_detect(grade, "[ABC]"),
    boro != "Missing"
  ) %>%
  mutate(boro = str_to_title(boro))
rest_inspec
```

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  pivot_wider(names_from = grade, values_from = n)
```

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() 
```

What about changing a label

```{r}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>%
  mutate(
    # arrange by order
    boro = fct_infreq(boro),
    # rename manhattan
    boro = fct_recode(boro, "The City" = "Manhattan")
    # wrong: boro = str_replace(boro, "Manhattan", "The City"), does not preserve order
  ) %>%
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar() 
```















